# Generated by Django 4.2.23 on 2025-09-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportinstance',
            old_name='created_at',
            new_name='date_of_the_report',
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='address_of_the_doctor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='name_of_the_doctor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
