// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXURbN6RQaIcEL02uNgIkaVvlpDtrXQ1k',
    appId: '1:196724508983:web:35d1ae38e69292b8ea72b2',
    messagingSenderId: '196724508983',
    projectId: 'hackathon-996b5',
    authDomain: 'hackathon-996b5.firebaseapp.com',
    storageBucket: 'hackathon-996b5.firebasestorage.app',
    measurementId: 'G-J89H6LJCW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6lVRqwmqmdf-W81U8Kje69OaZyl0bvI',
    appId: '1:196724508983:android:2a406c25bf7bd27bea72b2',
    messagingSenderId: '196724508983',
    projectId: 'hackathon-996b5',
    storageBucket: 'hackathon-996b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2PVvdz-anfKnFJV0WLVmvZYtpuZ7rrXY',
    appId: '1:196724508983:ios:91284da2263ededcea72b2',
    messagingSenderId: '196724508983',
    projectId: 'hackathon-996b5',
    storageBucket: 'hackathon-996b5.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );
}
